### ISSUE TITLE
Sound from jack is low

### ISSUE THREAD

**Issue by malexxx** [DantSu/Telmi-story-teller#1]
Sound from headphone with jack is too low.
We can't heard story on a car for example.
The difference in decibel between the main speaker and the jack semmes to be less important with Onion OS

Le son du casque branché sur la prise jack est trop faible.
On ne peux pas entendre correctement une histoire dans une voiture par exemple.
La différence de décibel entre le haut parleur et la prise jack semble moins importante avec Onion OS

**Comment by DantSu** [comment]
Je sais pas quoi repondre à ça... tu as paramétré le volume max à combien?
