### ISSUE TITLE
Add a locking mode for travel

### ISSUE THREAD

**Issue by malexxx** [DantSu/Telmi-story-teller#2]
Add the ability to lock buttons via a short press on the ON or Menu button

Ajouter la possibilité de verrouiller les boutons via un appui court sur le bouton ON ou Menu

For example see https://youtu.be/1DV54P9F7kM

**Comment by DantSu** [comment]
Feature intéressante, il faut que je réfléchisse.  Un petit cadenas dans un angle de l'écran. Un truc pour visualiser quand c'est bloqué.

**Comment by DantSu** [comment]
Je pense que c'est plutôt 3 longue secondes sur la touche menu pour activer le lock

**Comment by malexxx** [comment]
Oui, peu importe.
3 sec pour l'éteindre donc un clic pour le lock ou inversement
