### ISSUE TITLE
fast forward and rewind with L and R Key

### ISSUE THREAD

**Issue by malexxx** [DantSu/Telmi-story-teller#3]
Possibility to use L and R Key to fast forward and rewind

Possibilité d'utiliser les gachettes L et R pour faire un avance/retour rapide

**Comment by DantSu** [comment]
Je voos l'utilisation qu'en a ma fille et franchement ces gâchettes vont poser de gros soucis à chaque fois qu'elle va poser la console en écoutant les histoires, ça va faire des avances ou retours rapides. Les gachettes ne sont pas adaptées aux enfants de 3 ans et demi ~ 5 ans et demi.

**Comment by malexxx** [comment]
Pourquoi ne pas prévoir un mapping des touches personnalisable dans telmi sync alors ?
_Ma fille aimerai avoir la croix réservé à la navigation par exemple._

**Comment by DantSu** [comment]
Je ne me lancerai pas la dedans.

**Comment by DantSu** [comment]
Je ne me lancerai pas la dedans.
Mon but premier : Faire une interface simple et efficace pour les enfants et les parents. Faire des mapping de touche, c'est complètement à l'encontre du but initial de Telmi.
Regarde j'ai fait des paramêtres pour le volume max, tu ne l'as pas trouvé. J'ai fait une combinaison de 2 touches pour la luminosité de l'écran, pas trouvé non plus. Si je commence à rajouter des boutons et des raccourcis pour faire du mapping de touches, je perd les enfants et parents.
