### ISSUE TITLE
(Need SDL 2.6.0+) Progress Bar on stories when pausing, forwarding or rewinding

### ISSUE THREAD

**Issue by malexxx** [DantSu/Telmi-story-teller#4]
See a progress Bar on stories when pausing, forwarding or rewinding

Voir une barre de progression sur les histoires lorsqu'on mets sur pause, avance ou retour rapide

**Comment by DantSu** [comment]
Pas possible, on en a parlé... tu ne veux pas attendre sur Telmi sync que je convertisse tous les mp3 en 192kbps donc je ne peux pas connaître la durée d'un mp3.

**Comment by malexxx** [comment]
Oui, nous en avons déjà parlé.
Mais l'absence de cette fonctionnalité est un gros manque pour telmiOS.

Je pense que cette feature Request mériterai de rester ouverte pour ne pas l'oublier.

**Comment by malexxx** [comment]
OK, c'est toi le patron ;-)

**Comment by DantSu** [comment]
Need SDL 2.6.0 or newer (see #8)
