### ISSUE TITLE
Better navigation on music

### ISSUE THREAD

**Issue by malexxx** [DantSu/Telmi-story-teller#6]
Use left and right for switch album
up and down to switch track inside album

(need to solve issue #3 )

Utiliser les boutons gauche et droite pour changer d'album
Haut et bas pour changer de piste à l'intérieur de l'album

**Comment by malexxx** [comment]
idéalement la vue en mode musique serait un carrousel horizontal d'album
la navigation se ferai de droite à gauche
avec un seul album visible à l'écran et ses 
en dessous

**Comment by DantSu** [comment]
Je vois pas l'intérêt par rapport à la sélection actuelle d'album via le bouton menu.
