### ISSUE TITLE
Resume possibility

### ISSUE THREAD

**Issue by malexxx** [DantSu/Telmi-story-teller#7]
Add the possibility to resume the play at the last point like onionOS on his game

Ajouter la possibilité de reprendre la lecture au dernier point d'arret comme onionOS peux le proposer dans ses jeux.

**Comment by DantSu** [comment]
Comme actuellement quand la console se met en veille d'elle même, c'est ça ?

**Comment by malexxx** [comment]
Oui

**Comment by DantSu** [comment]
Ok j'implementerai ça. Quand on éteindra la console volontairement, on se retrouvera au même endroit à l'allumage.
